declare module 'svelte-feather-icons' {
  import { SvelteComponentTyped } from 'svelte';
  type FeatherIconPropsType = {
    size?: string;
    strokeWidth?: number;
    class?: string;
  };
  class FeatherIcons extends SvelteComponentTyped<FeatherIconPropsType> {}

  export class ActivityIcon extends FeatherIcons {}
  export class AirplayIcon extends FeatherIcons {}
  export class AlertCircleIcon extends FeatherIcons {}
  export class AlertOctagonIcon extends FeatherIcons {}
  export class AlertTriangleIcon extends FeatherIcons {}
  export class AlignCenterIcon extends FeatherIcons {}
  export class AlignJustifyIcon extends FeatherIcons {}
  export class AlignLeftIcon extends FeatherIcons {}
  export class AlignRightIcon extends FeatherIcons {}
  export class AnchorIcon extends FeatherIcons {}
  export class ApertureIcon extends FeatherIcons {}
  export class ArchiveIcon extends FeatherIcons {}
  export class ArrowDownCircleIcon extends FeatherIcons {}
  export class ArrowDownIcon extends FeatherIcons {}
  export class ArrowDownLeftIcon extends FeatherIcons {}
  export class ArrowDownRightIcon extends FeatherIcons {}
  export class ArrowLeftCircleIcon extends FeatherIcons {}
  export class ArrowLeftIcon extends FeatherIcons {}
  export class ArrowRightCircleIcon extends FeatherIcons {}
  export class ArrowRightIcon extends FeatherIcons {}
  export class ArrowUpCircleIcon extends FeatherIcons {}
  export class ArrowUpIcon extends FeatherIcons {}
  export class ArrowUpLeftIcon extends FeatherIcons {}
  export class ArrowUpRightIcon extends FeatherIcons {}
  export class AtSignIcon extends FeatherIcons {}
  export class AwardIcon extends FeatherIcons {}
  export class BarChart2Icon extends FeatherIcons {}
  export class BarChartIcon extends FeatherIcons {}
  export class BatteryChargingIcon extends FeatherIcons {}
  export class BatteryIcon extends FeatherIcons {}
  export class BellIcon extends FeatherIcons {}
  export class BellOffIcon extends FeatherIcons {}
  export class BluetoothIcon extends FeatherIcons {}
  export class BoldIcon extends FeatherIcons {}
  export class BookIcon extends FeatherIcons {}
  export class BookOpenIcon extends FeatherIcons {}
  export class BookmarkIcon extends FeatherIcons {}
  export class BoxIcon extends FeatherIcons {}
  export class BriefcaseIcon extends FeatherIcons {}
  export class CalendarIcon extends FeatherIcons {}
  export class CameraIcon extends FeatherIcons {}
  export class CameraOffIcon extends FeatherIcons {}
  export class CastIcon extends FeatherIcons {}
  export class CheckCircleIcon extends FeatherIcons {}
  export class CheckIcon extends FeatherIcons {}
  export class CheckSquareIcon extends FeatherIcons {}
  export class ChevronDownIcon extends FeatherIcons {}
  export class ChevronLeftIcon extends FeatherIcons {}
  export class ChevronRightIcon extends FeatherIcons {}
  export class ChevronUpIcon extends FeatherIcons {}
  export class ChevronsDownIcon extends FeatherIcons {}
  export class ChevronsLeftIcon extends FeatherIcons {}
  export class ChevronsRightIcon extends FeatherIcons {}
  export class ChevronsUpIcon extends FeatherIcons {}
  export class ChromeIcon extends FeatherIcons {}
  export class CircleIcon extends FeatherIcons {}
  export class ClipboardIcon extends FeatherIcons {}
  export class ClockIcon extends FeatherIcons {}
  export class CloudDrizzleIcon extends FeatherIcons {}
  export class CloudIcon extends FeatherIcons {}
  export class CloudLightningIcon extends FeatherIcons {}
  export class CloudOffIcon extends FeatherIcons {}
  export class CloudRainIcon extends FeatherIcons {}
  export class CloudSnowIcon extends FeatherIcons {}
  export class CodeIcon extends FeatherIcons {}
  export class CodepenIcon extends FeatherIcons {}
  export class CodesandboxIcon extends FeatherIcons {}
  export class CoffeeIcon extends FeatherIcons {}
  export class ColumnsIcon extends FeatherIcons {}
  export class CommandIcon extends FeatherIcons {}
  export class CompassIcon extends FeatherIcons {}
  export class CopyIcon extends FeatherIcons {}
  export class CornerDownLeftIcon extends FeatherIcons {}
  export class CornerDownRightIcon extends FeatherIcons {}
  export class CornerLeftDownIcon extends FeatherIcons {}
  export class CornerLeftUpIcon extends FeatherIcons {}
  export class CornerRightDownIcon extends FeatherIcons {}
  export class CornerRightUpIcon extends FeatherIcons {}
  export class CornerUpLeftIcon extends FeatherIcons {}
  export class CornerUpRightIcon extends FeatherIcons {}
  export class CpuIcon extends FeatherIcons {}
  export class CreditCardIcon extends FeatherIcons {}
  export class CropIcon extends FeatherIcons {}
  export class CrosshairIcon extends FeatherIcons {}
  export class DatabaseIcon extends FeatherIcons {}
  export class DeleteIcon extends FeatherIcons {}
  export class DiscIcon extends FeatherIcons {}
  export class DivideCircleIcon extends FeatherIcons {}
  export class DivideIcon extends FeatherIcons {}
  export class DivideSquareIcon extends FeatherIcons {}
  export class DollarSignIcon extends FeatherIcons {}
  export class DownloadCloudIcon extends FeatherIcons {}
  export class DownloadIcon extends FeatherIcons {}
  export class DribbbleIcon extends FeatherIcons {}
  export class DropletIcon extends FeatherIcons {}
  export class Edit2Icon extends FeatherIcons {}
  export class Edit3Icon extends FeatherIcons {}
  export class EditIcon extends FeatherIcons {}
  export class ExternalLinkIcon extends FeatherIcons {}
  export class EyeIcon extends FeatherIcons {}
  export class EyeOffIcon extends FeatherIcons {}
  export class FacebookIcon extends FeatherIcons {}
  export class FastForwardIcon extends FeatherIcons {}
  export class FeatherIcon extends FeatherIcons {}
  export class FigmaIcon extends FeatherIcons {}
  export class FileIcon extends FeatherIcons {}
  export class FileMinusIcon extends FeatherIcons {}
  export class FilePlusIcon extends FeatherIcons {}
  export class FileTextIcon extends FeatherIcons {}
  export class FilmIcon extends FeatherIcons {}
  export class FilterIcon extends FeatherIcons {}
  export class FlagIcon extends FeatherIcons {}
  export class FolderIcon extends FeatherIcons {}
  export class FolderMinusIcon extends FeatherIcons {}
  export class FolderPlusIcon extends FeatherIcons {}
  export class FramerIcon extends FeatherIcons {}
  export class FrownIcon extends FeatherIcons {}
  export class GiftIcon extends FeatherIcons {}
  export class GitBranchIcon extends FeatherIcons {}
  export class GitCommitIcon extends FeatherIcons {}
  export class GitMergeIcon extends FeatherIcons {}
  export class GitPullRequestIcon extends FeatherIcons {}
  export class GithubIcon extends FeatherIcons {}
  export class GitlabIcon extends FeatherIcons {}
  export class GlobeIcon extends FeatherIcons {}
  export class GridIcon extends FeatherIcons {}
  export class HardDriveIcon extends FeatherIcons {}
  export class HashIcon extends FeatherIcons {}
  export class HeadphonesIcon extends FeatherIcons {}
  export class HeartIcon extends FeatherIcons {}
  export class HelpCircleIcon extends FeatherIcons {}
  export class HexagonIcon extends FeatherIcons {}
  export class HomeIcon extends FeatherIcons {}
  export class ImageIcon extends FeatherIcons {}
  export class InboxIcon extends FeatherIcons {}
  export class InfoIcon extends FeatherIcons {}
  export class InstagramIcon extends FeatherIcons {}
  export class ItalicIcon extends FeatherIcons {}
  export class KeyIcon extends FeatherIcons {}
  export class LayersIcon extends FeatherIcons {}
  export class LayoutIcon extends FeatherIcons {}
  export class LifeBuoyIcon extends FeatherIcons {}
  export class Link2Icon extends FeatherIcons {}
  export class LinkIcon extends FeatherIcons {}
  export class LinkedinIcon extends FeatherIcons {}
  export class ListIcon extends FeatherIcons {}
  export class LoaderIcon extends FeatherIcons {}
  export class LockIcon extends FeatherIcons {}
  export class LogInIcon extends FeatherIcons {}
  export class LogOutIcon extends FeatherIcons {}
  export class MailIcon extends FeatherIcons {}
  export class MapIcon extends FeatherIcons {}
  export class MapPinIcon extends FeatherIcons {}
  export class Maximize2Icon extends FeatherIcons {}
  export class MaximizeIcon extends FeatherIcons {}
  export class MehIcon extends FeatherIcons {}
  export class MenuIcon extends FeatherIcons {}
  export class MessageCircleIcon extends FeatherIcons {}
  export class MessageSquareIcon extends FeatherIcons {}
  export class MicIcon extends FeatherIcons {}
  export class MicOffIcon extends FeatherIcons {}
  export class Minimize2Icon extends FeatherIcons {}
  export class MinimizeIcon extends FeatherIcons {}
  export class MinusCircleIcon extends FeatherIcons {}
  export class MinusIcon extends FeatherIcons {}
  export class MinusSquareIcon extends FeatherIcons {}
  export class MonitorIcon extends FeatherIcons {}
  export class MoonIcon extends FeatherIcons {}
  export class MoreHorizontalIcon extends FeatherIcons {}
  export class MoreVerticalIcon extends FeatherIcons {}
  export class MousePointerIcon extends FeatherIcons {}
  export class MoveIcon extends FeatherIcons {}
  export class MusicIcon extends FeatherIcons {}
  export class Navigation2Icon extends FeatherIcons {}
  export class NavigationIcon extends FeatherIcons {}
  export class OctagonIcon extends FeatherIcons {}
  export class PackageIcon extends FeatherIcons {}
  export class PaperclipIcon extends FeatherIcons {}
  export class PauseCircleIcon extends FeatherIcons {}
  export class PauseIcon extends FeatherIcons {}
  export class PenToolIcon extends FeatherIcons {}
  export class PercentIcon extends FeatherIcons {}
  export class PhoneCallIcon extends FeatherIcons {}
  export class PhoneForwardedIcon extends FeatherIcons {}
  export class PhoneIcon extends FeatherIcons {}
  export class PhoneIncomingIcon extends FeatherIcons {}
  export class PhoneMissedIcon extends FeatherIcons {}
  export class PhoneOffIcon extends FeatherIcons {}
  export class PhoneOutgoingIcon extends FeatherIcons {}
  export class PieChartIcon extends FeatherIcons {}
  export class PlayCircleIcon extends FeatherIcons {}
  export class PlayIcon extends FeatherIcons {}
  export class PlusCircleIcon extends FeatherIcons {}
  export class PlusIcon extends FeatherIcons {}
  export class PlusSquareIcon extends FeatherIcons {}
  export class PocketIcon extends FeatherIcons {}
  export class PowerIcon extends FeatherIcons {}
  export class PrinterIcon extends FeatherIcons {}
  export class RadioIcon extends FeatherIcons {}
  export class RefreshCcwIcon extends FeatherIcons {}
  export class RefreshCwIcon extends FeatherIcons {}
  export class RepeatIcon extends FeatherIcons {}
  export class RewindIcon extends FeatherIcons {}
  export class RotateCcwIcon extends FeatherIcons {}
  export class RotateCwIcon extends FeatherIcons {}
  export class RssIcon extends FeatherIcons {}
  export class SaveIcon extends FeatherIcons {}
  export class ScissorsIcon extends FeatherIcons {}
  export class SearchIcon extends FeatherIcons {}
  export class SendIcon extends FeatherIcons {}
  export class ServerIcon extends FeatherIcons {}
  export class SettingsIcon extends FeatherIcons {}
  export class Share2Icon extends FeatherIcons {}
  export class ShareIcon extends FeatherIcons {}
  export class ShieldIcon extends FeatherIcons {}
  export class ShieldOffIcon extends FeatherIcons {}
  export class ShoppingBagIcon extends FeatherIcons {}
  export class ShoppingCartIcon extends FeatherIcons {}
  export class ShuffleIcon extends FeatherIcons {}
  export class SidebarIcon extends FeatherIcons {}
  export class SkipBackIcon extends FeatherIcons {}
  export class SkipForwardIcon extends FeatherIcons {}
  export class SlackIcon extends FeatherIcons {}
  export class SlashIcon extends FeatherIcons {}
  export class SlidersIcon extends FeatherIcons {}
  export class SmartphoneIcon extends FeatherIcons {}
  export class SmileIcon extends FeatherIcons {}
  export class SpeakerIcon extends FeatherIcons {}
  export class SquareIcon extends FeatherIcons {}
  export class StarIcon extends FeatherIcons {}
  export class StopCircleIcon extends FeatherIcons {}
  export class SunIcon extends FeatherIcons {}
  export class SunriseIcon extends FeatherIcons {}
  export class SunsetIcon extends FeatherIcons {}
  export class TabletIcon extends FeatherIcons {}
  export class TagIcon extends FeatherIcons {}
  export class TargetIcon extends FeatherIcons {}
  export class TerminalIcon extends FeatherIcons {}
  export class ThermometerIcon extends FeatherIcons {}
  export class ThumbsDownIcon extends FeatherIcons {}
  export class ThumbsUpIcon extends FeatherIcons {}
  export class ToggleLeftIcon extends FeatherIcons {}
  export class ToggleRightIcon extends FeatherIcons {}
  export class ToolIcon extends FeatherIcons {}
  export class Trash2Icon extends FeatherIcons {}
  export class TrashIcon extends FeatherIcons {}
  export class TrelloIcon extends FeatherIcons {}
  export class TrendingDownIcon extends FeatherIcons {}
  export class TrendingUpIcon extends FeatherIcons {}
  export class TriangleIcon extends FeatherIcons {}
  export class TruckIcon extends FeatherIcons {}
  export class TvIcon extends FeatherIcons {}
  export class TwitchIcon extends FeatherIcons {}
  export class TwitterIcon extends FeatherIcons {}
  export class TypeIcon extends FeatherIcons {}
  export class UmbrellaIcon extends FeatherIcons {}
  export class UnderlineIcon extends FeatherIcons {}
  export class UnlockIcon extends FeatherIcons {}
  export class UploadCloudIcon extends FeatherIcons {}
  export class UploadIcon extends FeatherIcons {}
  export class UserCheckIcon extends FeatherIcons {}
  export class UserIcon extends FeatherIcons {}
  export class UserMinusIcon extends FeatherIcons {}
  export class UserPlusIcon extends FeatherIcons {}
  export class UserXIcon extends FeatherIcons {}
  export class UsersIcon extends FeatherIcons {}
  export class VideoIcon extends FeatherIcons {}
  export class VideoOffIcon extends FeatherIcons {}
  export class VoicemailIcon extends FeatherIcons {}
  export class Volume1Icon extends FeatherIcons {}
  export class Volume2Icon extends FeatherIcons {}
  export class VolumeIcon extends FeatherIcons {}
  export class VolumeXIcon extends FeatherIcons {}
  export class WatchIcon extends FeatherIcons {}
  export class WifiIcon extends FeatherIcons {}
  export class WifiOffIcon extends FeatherIcons {}
  export class WindIcon extends FeatherIcons {}
  export class XCircleIcon extends FeatherIcons {}
  export class XIcon extends FeatherIcons {}
  export class XOctagonIcon extends FeatherIcons {}
  export class XSquareIcon extends FeatherIcons {}
  export class YoutubeIcon extends FeatherIcons {}
  export class ZapIcon extends FeatherIcons {}
  export class ZapOffIcon extends FeatherIcons {}
  export class ZoomInIcon extends FeatherIcons {}
  export class ZoomOutIcon extends FeatherIcons {}
}
